<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="CheckList.aspx.cs" Inherits="BuyList.Registros.CheckList" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

     <div class="container">
        <ul class="nav justify-content-center bg-success">
            <li>
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
                <h5 class="text-light">Check List</h5>
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
            </li>
        </ul>
        <br />
        <div class="form-row">
            <div class="col-2 col-lg-1 offset-2">
                <label for="CheckListId"><strong>Codigo</strong></label>
            </div>
            <div class="col-6 col-lg-5">
                <asp:TextBox ID="CheckListIdTextBox" runat="server" Text="0" TextMode="Search" CssClass="col-sm-12 col-md-12 form-control" />
            </div>
            <div class="col-2 col-lg-3">
                <asp:LinkButton ID="Buscar" runat="server" CssClass="col-md-4 offset-0 " OnClick="Buscar_Click"><i class="fas fa-search fa-2x"></i></asp:LinkButton>
            </div>
        </div>
        
        <div class="form-row">
            
            <div class="col">
             <label for="Cliente"><strong>Cliente</strong></label>
            <asp:DropDownList ID="ClienteDropDownList" runat="server" CssClass="form-control">
            </asp:DropDownList>
            </div>

            <div class="col">
             <label for="Categoria"><strong>Categoria</strong></label>
            <asp:DropDownList ID="ListaDropDownList" runat="server" CssClass="form-control">
            </asp:DropDownList>
            </div>


            <div class="col-1">
                <br />      
               <asp:LinkButton runat="server" CssClass="col-3" OnClick="Actualizar_Click" ><i class="fas fa-undo-alt fa-2x"></i></asp:LinkButton>    

            </div>
        </div>

          <hr />
         <div class="row">
             <div class="col-9">
                 <asp:GridView ID="ListaGridView" class="col" runat="server" DataKeyNames="DetalleListaId" AllowPaging="true" PageSize="10" ShowHeaderWhenEmpty="false" AutoGenerateDeleteButton="true" CellPadding="4" ForeColor="#333333" GridLines="None" Width="767px" AutoGenerateColumns="true" OnRowDeleting="Grid_RowDeleting" OnSelectedIndexChanged="ListaGridView_SelectedIndexChanged">
                     <AlternatingRowStyle BackColor="White" />

                     <EditRowStyle BackColor="#2461BF" />
                     <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                     <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                     <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                     <RowStyle BackColor="#EFF3FB" />
                     <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                     <SortedAscendingCellStyle BackColor="#F5F7FB" />
                     <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                     <SortedDescendingCellStyle BackColor="#E9EBEF" />
                     <SortedDescendingHeaderStyle BackColor="#4870BE" />
                 <Columns>
                     <asp:TemplateField HeaderText="Slect">
                         <ItemTemplate>
                             <asp:CheckBox runat="server" />
                         </ItemTemplate>
                     </asp:TemplateField>
                 </Columns>
                 </asp:GridView>

             </div>
             <div class="col-3">
                 <div class="form-row">
                     <div class="col-12">
                         <label for="SubTotal"><strong>SubTotal</strong></label>
                         <asp:TextBox ID="SubTotalTextBox" CssClass="form-control" placeholder="0" runat="server" ReadOnly="True" />
                     </div>
                 </div>

                 <div class="form-row">
                     <div class="col-12">
                         <label for="Itebis"><strong>Itebis</strong></label>
                         <asp:TextBox ID="ItebisTotalTextBox" CssClass="form-control" placeholder="0" runat="server" ReadOnly="True" />
                     </div>
                 </div>
                 <div class="form-row">
                     <div class="col-12">
                         <label for="Total"><strong>Total</strong></label>
                         <asp:TextBox ID="TotalTextBox" CssClass="form-control" placeholder="0" runat="server" ReadOnly="True" />
                     </div>
                 </div>
             </div>
         </div>
         
          <hr />
        <div class="col offset-3">
            <asp:LinkButton ID="Limpiara" runat="server" CssClass=" btn btn-primary col-6 col-sm-2" OnClick="Limpiar_Click"><i class="fas fa-broom"></i>  Limpiar</asp:LinkButton>
            <asp:LinkButton ID="Guarda" runat="server" CssClass=" btn btn-success col-6 col-sm-2" OnClick="Guardar_Click"><i class="fas fa-save"></i>  Guardar</asp:LinkButton>
            <asp:LinkButton ID="Elimina" runat="server" CssClass="btn btn-danger col-6 col-sm-2 " OnClick="Eliminar_Click"><i class="fas fa-trash-alt"></i>  Eliminar</asp:LinkButton>
        </div>
       

        </div>

             
   

</asp:Content>
